name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: |
        rustup show
        rustup component add rust-src clippy

    - uses: actions-rs/clippy-check@v1
      env:
        BASEDIR: "."
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install --yes make mtools parted
        rustup show
        rustup component add rust-src

    - name: Build UEFI application
      run: make
